services:
  backend:
    container_name: django-backend
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./docker/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app:z  # mirrors the changes made in the app folder to the container an vice versa
      - dev-static-data:/vol/web
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
#        sh -c "python manage.py wait_for_db &&
#            python manage.py migrate &&
#            python manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.envs/.dev/.django
      - ./.envs/.dev/.postgres

volumes:
  dev-static-data: