---
name: CI Backend - Lint, Test

on:
  push:
    branches: main

jobs: 
  lint-test-coverage:
    name: Lint, Test, and Coverage
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        # This step renames the .envs/.dev-example/ folder to .envs/.dev/
        # the .envs/.dev/ is used in docker-compose file
        name: Rename .envs/.dev-example/ folder to .envs/.dev/
        run: mv .envs/.dev-example .envs/.dev
      - 
        name: Lint
        run: docker-compose run --rm backend sh -c "flake8"
      - 
        # run test and collect coverage data, we need to run this as root
        # this solves the permission issues, 
        # coverage needs user to own the directory where .coverage file is located
        # since I dont want to add a new directory in Docker, 
        # runnign this command as root user seems a good alternative
        # other solution would be creating a directory in Dockerfile
        # that is owned by djanog-user and save the .coverage file there
        # then also adjusting docker compose and making this directory
        # persistant if we woudl want to run command with --rm (removing containers at the end)
        name: Test
        run: docker-compose run --rm backend --user root sh -c "python manage.py wait_for_db && 
                                                                coverage run manage.py test"
      -
        # also running as root user this command to solve the issues with permissions
        name: Generate coverage XML reports
        run: docker-compose run --rm backend --user root sh -c "coverage xml"
      - 
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN_CHATVIBE }}
          slug: artursniegowski/ChatVibe
        