---
name: CI Backend

on:
  push:
    branches: main

jobs: 
  lint-test-coverage:
    name: Lint, Test, and Coverage
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Rename .envs/.dev-example/ folder to .envs/.dev/
        run: mv .envs/.dev-example .envs/.dev
        # This step renames the .envs/.dev-example/ folder to .envs/.dev/
        # the .envs/.dev/ is used in docker-compose file
      - 
        name: Lint
        run: docker-compose run --rm backend sh -c "flake8"
      - 
        name: Create coverage directory
        run: mkdir -p cov/
        # this is needed only for github-actions as the .coverage cant be
        # created by another user than the user specified in the docker and
        # this would lead to persmissions issues
      - 
        name: Test
        run: docker-compose run --rm backend sh -c "python manage.py wait_for_db && 
                                                    coverage run --rcfile=cov/.coverage manage.py test"
        # run test and collect coverage data,
        # save the .coverage reports in the cov/ directory to avoid the 
        # permissions issues
      -
        name: Generate coverage XML reports
        run: docker-compose run --rm backend sh -c "coverage xml -o cov/coverage.xml"
      - 
        name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN_CHATVIBE }}
          slug: artursniegowski/ChatVibe
          files: cov/coverage.xml
        